import tkinter as tk

janela = tk.Tk()
janela.geometry('1000x500+100+100')
janela.title('SUPER AÇAI')

Frame_Top = tk.Frame()
Frame_Top.place(relx= 0,rely=0.003,relwidth=1, relheight=1)
Frame_Top.configure(relief='groove')
Frame_Top.configure(borderwidth = '8')
Frame_Top.configure(relief="groove")
Frame_Top.configure(background="#6d32a8")

label_nome = tk.Label()
label_nome.place(relx= 0.005,rely=0.01,relwidth=1, relheight=0.08)
label_nome.configure(background="#d9d9d9")
label_nome.configure(disabledforeground="black")
label_nome.configure(font='-family{arial black}- size 50')
label_nome.configure(foreground='black')
label_nome.configure(relief= 'raised')
label_nome.configure(borderwidth = '5')
label_nome.configure(relief="raised")
label_nome.configure(text="SUPER AÇAI")


Frame_left = tk.Frame(Frame_Top)
Frame_left.place(relx= 0,rely=0.08,relwidth=0.354, relheight=0.645)
Frame_left.configure(relief= 'raised')
Frame_left.configure(borderwidth = '8')
Frame_left.configure(relief="raised")
Frame_left.configure(background="white")

Frame_mid = tk.Frame(Frame_Top)
Frame_mid.place(relx= 0.347,rely=0.08,relwidth=0.354, relheight=0.645)
Frame_mid.configure(relief= 'raised')
Frame_mid.configure(borderwidth = '8')
Frame_mid.configure(relief="raised")
Frame_mid.configure(background="white")

Frame_bottom = tk.Frame(Frame_Top)
Frame_bottom.place(relx= 0,rely=0.72,relwidth=0.7, relheight=0.28)
Frame_bottom.configure(relief= 'raised')
Frame_bottom.configure(borderwidth = '8')
Frame_bottom.configure(relief="raised")
Frame_bottom.configure(background="#e0a4ed")

Frame_right = tk.Frame(Frame_Top)
Frame_right.place(relx= 0.697,rely=0.080,relwidth=0.31, relheight=0.38)
Frame_right.configure(relief= 'raised')
Frame_right.configure(borderwidth = '8')
Frame_right.configure(relief="raised")
Frame_right.configure(background="white")

Frame_bot_right = tk.Frame(Frame_Top)
Frame_bot_right.place(relx= 0.697,rely=0.43,relwidth=0.31, relheight=0.5)
Frame_right.configure(relief= 'raised')
Frame_bot_right.configure(borderwidth = '8')
Frame_bot_right.configure(relief="raised")
Frame_bot_right.configure(background="white")

#criando listbox
acai_listbox = tk.Listbox(Frame_bottom)
acai_listbox.place(relx= 0.3,rely=0.05,relwidth=0.2, relheight=0.2)
acai_listbox.configure(background="#d9d9d9")
acai_listbox.configure(disabledforeground="grey")
acai_listbox.configure(font='-family{arial}-size 14')
acai_listbox.configure(foreground='black')
acai_listbox.configure(highlightbackground="black")
acai_listbox.configure(highlightcolor= "black")
acai_listbox.configure(borderwidth = '5')
acai_listbox.configure(justify="right")

adicionais = tk.Listbox(Frame_bottom)
adicionais.place(relx= 0.3,rely=0.29,relwidth=0.2, relheight=0.2)
adicionais.configure(background="#d9d9d9")
adicionais.configure(disabledforeground="grey")
adicionais.configure(font='-family{arial}-size 14')
adicionais.configure(foreground='black')
adicionais.configure(highlightbackground="black")
adicionais.configure(highlightcolor= "black")
adicionais.configure(borderwidth = '5')
adicionais.configure(justify="right")

valores = tk.Listbox(Frame_bottom)
valores.place(relx= 0.3,rely=0.54,relwidth=0.2, relheight=0.2)
valores.configure(background="#d9d9d9")
valores.configure(disabledforeground="black")
valores.configure(font='-family{arial}-size 14')
valores.configure(foreground='black')
valores.configure(highlightbackground="black")
valores.configure(highlightcolor= "black")
valores.configure(borderwidth = '5')
valores.configure(justify="right")

dinheiro_entry = tk.Entry(Frame_bottom)
dinheiro_entry.place(relx= 0.3,rely=0.78,relwidth=0.2, relheight=0.2)
dinheiro_entry.configure(background="#d9d9d9")
dinheiro_entry.configure(disabledforeground="black")
dinheiro_entry.configure(font='-family{arial}-size 14')
dinheiro_entry.configure(foreground='black')
dinheiro_entry.configure(highlightbackground="black")
dinheiro_entry.configure(highlightcolor= "black")
dinheiro_entry.configure(borderwidth = '5')
dinheiro_entry.configure(justify="left")

total = tk.Listbox(Frame_bottom)
total.place(relx= 0.75,rely=0.05,relwidth=0.2, relheight=0.2)
total.configure(background="#d9d9d9")
total.configure(disabledforeground="black")
total.configure(font='-family{arial}-size 14')
total.configure(foreground='black')
total.configure(highlightbackground="black")
total.configure(highlightcolor= "black")
total.configure(borderwidth = '5')
total.configure(justify="right")

troco = tk.Listbox(Frame_bottom)
troco.place(relx=0.75,rely=0.27,relwidth=0.2, relheight=0.2)
troco.configure(background="#d9d9d9")
troco.configure(disabledforeground="black")
troco.configure(font='-family{arial}-size 14')
troco.configure(foreground='black')
troco.configure(highlightbackground="black")
troco.configure(highlightcolor= "black")
troco.configure(borderwidth = '5')
troco.configure(justify="right")

recibo = tk.Listbox(Frame_bot_right)
recibo.place(relx= 0,rely=0,relwidth=1, relheight=1)
recibo.configure(background="#f7f7cb")
recibo.configure(disabledforeground="black")
recibo.configure(font='-family{arial}-size 10')
recibo.configure(foreground='black')
recibo.configure(highlightbackground="black")
recibo.configure(highlightcolor= "black")
recibo.configure(borderwidth = '5')

calculadora_entry = tk.Entry(Frame_right)
calculadora_entry.place(relx= 0.02,rely=0.03,relwidth=71, relheight=45, bordermode='ignore')
calculadora_entry.configure(background="#d9d9d9")
calculadora_entry.configure(disabledforeground="black")
calculadora_entry.configure(font='-family{arial}-size 14')
calculadora_entry.configure(foreground='black')
calculadora_entry.configure(highlightbackground="black")
calculadora_entry.configure(highlightcolor= "black")
calculadora_entry.configure(borderwidth = '5')
calculadora_entry.configure(justify="right")

#CRIANDO OS TIPOS DE AÇAI

acai_300ml_entry = tk.Entry(Frame_left)
acai_300ml_entry.place(relx= 0.7,rely=0.1,relwidth=0.2, height=35, bordermode='ignore')
acai_300ml_entry.configure(background="#d9d9d9")
acai_300ml_entry.configure(disabledforeground="black")
acai_300ml_entry.configure(font='-family{arial}-size 14')
acai_300ml_entry.configure(foreground='black')
acai_300ml_entry.configure(insertbackground="black")
acai_300ml_entry.configure(borderwidth = '5')

acai_500ml_entry = tk.Entry(Frame_left)
acai_500ml_entry.place(relx= 0.7,rely=0.5,relwidth=0.2, height=35, bordermode='ignore')
acai_500ml_entry.configure(background="#d9d9d9")
acai_500ml_entry.configure(disabledforeground="black")
acai_500ml_entry.configure(font='-family{arial}-size 14')
acai_500ml_entry.configure(foreground='black')
acai_500ml_entry.configure(insertbackground="black")
acai_500ml_entry.configure(borderwidth = '5')

acai_700ml_entry = tk.Entry(Frame_left)
acai_700ml_entry.place(relx= 0.7,rely=0.3,relwidth=0.2, height=35, bordermode='ignore')
acai_700ml_entry.configure(background="#d9d9d9")
acai_700ml_entry.configure(disabledforeground="black")
acai_700ml_entry.configure(font='-family{arial}-size 14')
acai_700ml_entry.configure(foreground='black')
acai_700ml_entry.configure(insertbackground="black")
acai_700ml_entry.configure(borderwidth = '5')

#CRIANDO OS BOTÕES

botao_total = tk.Button()
botao_total.place(relx= 0.699,rely=0.92,width=100, height=45)
botao_total.configure(activeforeground='#ececec')
botao_total.configure(activebackground='black')
botao_total.configure(background="#d9d9d9")
botao_total.configure(borderwidth = '5')
botao_total.configure(disabledforeground="grey")
botao_total.configure(font='-family{segoe UI}-size 14')
botao_total.configure(foreground='black')
botao_total.configure(highlightbackground="grey")
botao_total.configure(highlightcolor= "black")
botao_total.configure(pady='0')
botao_total.configure(text='TOTAL')

botao_recibo = tk.Button()
botao_recibo.place(relx= 0.773,rely=0.92,width=100, height=45)
botao_recibo.configure(activeforeground='#ececec')
botao_recibo.configure(activebackground='black')
botao_recibo.configure(background="#d9d9d9")
botao_recibo.configure(borderwidth = '5')
botao_recibo.configure(disabledforeground="grey")
botao_recibo.configure(font='-family{segoe UI}-size 14')
botao_recibo.configure(foreground='black')
botao_recibo.configure(highlightbackground="grey")
botao_recibo.configure(highlightcolor= "black")
botao_recibo.configure(pady='0')
botao_recibo.configure(text='RECIBO')

botao_limpar = tk.Button()
botao_limpar.place(relx= 0.848,rely=0.92,width=90, height=45)
botao_limpar.configure(activeforeground='#ececec')
botao_limpar.configure(activebackground='black')
botao_limpar.configure(background="#d9d9d9")
botao_limpar.configure(borderwidth = '5')
botao_limpar.configure(disabledforeground="grey")
botao_limpar.configure(font='-family{segoe UI}-size 14')
botao_limpar.configure(foreground='black')
botao_limpar.configure(highlightbackground="grey")
botao_limpar.configure(highlightcolor= "black")
botao_limpar.configure(pady='0')
botao_limpar.configure(text='LIMPAR')

botao_sair = tk.Button()
botao_sair .place(relx= 0.92,rely=0.92,width=100, height=45)
botao_sair.configure(activeforeground='#ececec')
botao_sair.configure(activebackground='black')
botao_sair.configure(background="#d9d9d9")
botao_sair.configure(borderwidth = '5')
botao_sair.configure(disabledforeground="grey")
botao_sair.configure(font='-family{segoe UI}-size 14')
botao_sair.configure(highlightbackground="grey")
botao_sair.configure(highlightcolor= "black")
botao_sair.configure(pady='0')
botao_sair.configure(text='SAIR')
#botao_sair.configure(command=m.sair_janela)

####
custo_acai = tk.Label(Frame_bottom)
custo_acai.place(relx=0.01, rely=0.1, height= 25, width=200, bordermode='ignore')
custo_acai.configure(background='#e394d2')
custo_acai.configure(disabledforeground ='#a3a3a3')
custo_acai.configure(font='-family{segoe UI}-size 14')
custo_acai.configure(foreground='black')
custo_acai.configure(text='Custo do Açai')

custo_adicionais= tk.Label(Frame_bottom)
custo_adicionais.place(relx=0.01, rely=0.3, height= 25, width=200, bordermode='ignore')
custo_adicionais.configure(background='#e394d2')
custo_adicionais.configure(disabledforeground ='#a3a3a3')
custo_adicionais.configure(font='-family{segoe UI}-size 14')
custo_adicionais.configure(foreground='black')
custo_adicionais.configure(text='Custo dos adicionais')

sub_total= tk.Label(Frame_bottom)
sub_total.place(relx=0.01, rely=0.52, height=25, width=200, bordermode='ignore')
sub_total.configure(background='#e394d2')
sub_total.configure(disabledforeground='grey')
sub_total.configure(font='-family{segoe UI}-size 14')
sub_total.configure(foreground='black')
sub_total.configure(text='Sub Total')

dinheiro = tk.Label(Frame_bottom)
dinheiro.place(relx=0.01, rely=0.73, height=25, width=200, bordermode='ignore')
dinheiro.configure(background='#e394d2')
dinheiro.configure(disabledforeground='grey')
dinheiro.configure(font='-family{segoe UI}-size 14')
dinheiro.configure(foreground='black')
dinheiro.configure(text='Dinheiro')

total= tk.Label(Frame_bottom)
total.place(relx=0.52, rely=0.10, height=25, width=150, bordermode='ignore')
total.configure(background='#e394d2')
total.configure(disabledforeground='grey')
total.configure(font='-family{segoe UI}-size 14')
total.configure(foreground='black')
total.configure(text='Custo Total')

troco = tk.Label(Frame_bottom)
troco.place(relx=0.52, rely=0.31, height=25, width=150, bordermode='ignore')
troco.configure(background='#e394d2')
troco.configure(disabledforeground='grey')
troco.configure(font='-family{segoe UI}-size 14')
troco.configure(foreground='black')
troco.configure(text='Troco')

label_acai = tk.Label(Frame_left)
label_acai.place(relx=0, rely=0.0, relheight=0.08, width=130)
label_acai.configure(background='white')
label_acai.configure(borderwidth='4')
label_acai.configure(disabledforeground='grey')
label_acai.configure(font='-family {arial black} -size 14 -weight bold')
label_acai.configure(foreground='black')
label_acai.configure(text=' Açais :')

label_quantidade_acai = tk.Label(Frame_left)
label_quantidade_acai.place(relx=0.6, rely=0.0, relheight=0.08, width=130)
label_quantidade_acai.configure(background='white')
label_quantidade_acai.configure(borderwidth='4')
label_quantidade_acai.configure(disabledforeground='grey')
label_quantidade_acai.configure(font='-family {arial } -size 12 -weight bold')
label_quantidade_acai.configure(foreground='black')
label_quantidade_acai.configure(text='Quantidade :')


label_adicionais = tk.Label(Frame_mid)
label_adicionais.place(relx=0, rely=0.0, relheight=0.08, width=130)
label_adicionais.configure(background='white')
label_adicionais.configure(borderwidth='4')
label_adicionais.configure(disabledforeground='grey')
label_adicionais.configure(font='-family {arial black} -size 14 -weight bold')
label_adicionais.configure(foreground='black')
label_adicionais.configure(text='Adicionais :')

#check button acai
botao_acai300ml = tk.Checkbutton(Frame_left)
botao_acai300ml.configure(text= 'Açai 300ml')
#botao_acai300ml.configure(varaible=var1)
botao_acai300ml.place(relx=0.1, rely=0.1, height=35, bordermode= 'ignore')
botao_acai300ml.configure(font='-family {arial black} -size 14 -weight bold')
botao_acai300ml.configure(background='white')
#botao_acai300ml.configure(command=m.acai300ml)

botao_acai500ml = tk.Checkbutton(Frame_left)
botao_acai500ml.configure(text= 'Açai 500ml ')
#botao_acai500ml.configure(varaible=var2)
botao_acai500ml.place(relx=0.1, rely=0.3, height=35, bordermode= 'ignore')
botao_acai500ml.configure(font='-family {arial black} -size 14')
botao_acai500ml.configure(background='white')
#botao_acai500ml.configure(command=m.acai500ml)

botao_acai700ml = tk.Checkbutton(Frame_left)
botao_acai700ml.configure(text= 'Açai 700ml')
#botao_acai700ml.configure(varaible=var3)
botao_acai700ml.place(relx=0.1, rely=0.5, height=35, bordermode= 'ignore')
botao_acai700ml.configure(font='-family {arial black} -size 14')
botao_acai700ml.configure(background='white')
#botao_acai700ml.configure(command=m.acai700ml)

#check button adicionais
botao_leite = tk.Checkbutton(Frame_mid)
botao_leite.configure(text= 'Leite ')
#botao_leite.configure(varaible=var4)
botao_leite.place(relx=0.1, rely=0.1, height=35, bordermode= 'ignore')
botao_leite.configure(font='-family {arial black} -size 10')
botao_leite.configure(background='white')
#botao_leite.configure(command=m.leite)


botao_leite_cond = tk.Checkbutton(Frame_mid)
botao_leite_cond.configure(text= 'Leite condensado ')
#botao_leite_cond.configure(varaible=var5)
botao_leite_cond.place(relx=0.1, rely=0.2, height=35, bordermode= 'ignore')
botao_leite_cond.configure(font='-family {arial black} -size 10')
botao_leite_cond.configure(background='white')
#botao_leite.configure(command=m.leite_cond)

botao_pacoca = tk.Checkbutton(Frame_mid)
botao_pacoca.configure(text= 'Morango')
#botao_pacoca.configure(varaible=var6)
botao_pacoca.place(relx=0.1, rely=0.3, height=35, bordermode= 'ignore')
botao_pacoca.configure(font='-family {arial black} -size 10')
botao_pacoca.configure(background='white')
#botao_morango.configure(command=botao_pacoca)

botao_morango = tk.Checkbutton(Frame_mid)
botao_morango.configure(text= 'Morango')
#botao_morango.configure(varaible=var6)
botao_morango.place(relx=0.1, rely=0.4, height=35, bordermode= 'ignore')
botao_morango.configure(font='-family {arial black} -size 10')
botao_morango.configure(background='white')
#botao_morango.configure(command=m.morango)

botao_banana = tk.Checkbutton(Frame_mid)
botao_banana.configure(text= 'Banana')
#botao_banana.configure(varaible=var6)
botao_banana.place(relx=0.1, rely=0.5, height=35, bordermode= 'ignore')
botao_banana.configure(font='-family {arial black} -size 10')
botao_banana.configure(background='white')
#botao_banana.configure(command=m.banana)

botao_granola = tk.Checkbutton(Frame_mid)
botao_granola.configure(text= 'Granola')
#botao_granola.configure(varaible=var7)
botao_granola.place(relx=0.1, rely=0.6, height=35, bordermode= 'ignore')
botao_granola.configure(font='-family {arial black} -size 10')
botao_granola.configure(background='white')
#botao_granola.configure(command=m.granola)

botao_nutela = tk.Checkbutton(Frame_mid)
botao_nutela.configure(text= 'Nutela ')
#botao_nutela.configure(varaible=var8)
botao_nutela.place(relx=0.1, rely=0.7, height=35, bordermode= 'ignore')
botao_nutela.configure(font='-family {arial black} -size 10')
botao_nutela.configure(background='white')
#botao_nutela.configure(command=m.nutela)

#botões calculadorabotao_n1 =
botao_n0 = tk.Button()
botao_n0 .place(relx= 0.70,rely=0.368,width=100, height=45)
botao_n0.configure(activebackground='black')
botao_n0.configure(background="#d9d9d9")
botao_n0.configure(borderwidth = '5')
botao_n0.configure(disabledforeground="grey")
botao_n0.configure(font='-family{arial}-size 18')
botao_n0.configure(highlightbackground="grey")
botao_n0.configure(highlightcolor= "black")
botao_n0.configure(pady='0')
botao_n0.configure(text='0')
#botao_sair.configure(command=m.n1)


botao_n1 = tk.Button()
botao_n1 .place(relx= 0.70,rely=0.3,width=100, height=45)
botao_n1.configure(activebackground='black')
botao_n1.configure(background="#d9d9d9")
botao_n1.configure(borderwidth = '5')
botao_n1.configure(disabledforeground="grey")
botao_n1.configure(font='-family{arial}-size 18')
botao_n1.configure(highlightbackground="grey")
botao_n1.configure(highlightcolor= "black")
botao_n1.configure(pady='0')
botao_n1.configure(text='1')
#botao_sair.configure(command=m.n1)

botao_n2 = tk.Button()
botao_n2 .place(relx= 0.774,rely=0.3,width=100, height=45)
botao_n2.configure(activebackground='black')
botao_n2.configure(background="#d9d9d9")
botao_n2.configure(borderwidth = '5')
botao_n2.configure(disabledforeground="grey")
botao_n2.configure(font='-family{arial}-size 18')
botao_n2.configure(highlightbackground="grey")
botao_n2.configure(highlightcolor= "black")
botao_n2.configure(pady='0')
botao_n2.configure(text='2')
#botao_sair.configure(command=m.n1)

botao_n3 = tk.Button()
botao_n3 .place(relx= 0.847,rely=0.3,width=100, height=45)
botao_n3.configure(activebackground='black')
botao_n3.configure(background="#d9d9d9")
botao_n3.configure(borderwidth = '5')
botao_n3.configure(disabledforeground="grey")
botao_n3.configure(font='-family{arial}-size 18')
botao_n3.configure(highlightbackground="grey")
botao_n3.configure(highlightcolor= "black")
botao_n3.configure(pady='0')
botao_n3.configure(text='3')
#botao_sair.configure(command=m.n1)

botao_n4 = tk.Button()
botao_n4 .place(relx= 0.70,rely=0.235,width=100, height=45)
botao_n4.configure(activebackground='black')
botao_n4.configure(background="#d9d9d9")
botao_n4.configure(borderwidth = '5')
botao_n4.configure(disabledforeground="grey")
botao_n4.configure(font='-family{arial}-size 18')
botao_n4.configure(highlightbackground="grey")
botao_n4.configure(highlightcolor= "black")
botao_n4.configure(pady='0')
botao_n4.configure(text='4')
#botao_sair.configure(command=m.n1)

botao_n5 = tk.Button()
botao_n5 .place(relx= 0.774,rely=0.235,width=100, height=45)
botao_n5.configure(activebackground='black')
botao_n5.configure(background="#d9d9d9")
botao_n5.configure(borderwidth = '5')
botao_n5.configure(disabledforeground="grey")
botao_n5.configure(font='-family{arial}-size 18')
botao_n5.configure(highlightbackground="grey")
botao_n5.configure(highlightcolor= "black")
botao_n5.configure(pady='0')
botao_n5.configure(text='5')
#botao_sair.configure(command=m.n1)

botao_n6 = tk.Button()
botao_n6 .place(relx= 0.847,rely=0.235,width=100, height=45)
botao_n6.configure(activebackground='black')
botao_n6.configure(background="#d9d9d9")
botao_n6.configure(borderwidth = '5')
botao_n6.configure(disabledforeground="grey")
botao_n6.configure(font='-family{arial}-size 18')
botao_n6.configure(highlightbackground="grey")
botao_n6.configure(highlightcolor= "black")
botao_n6.configure(pady='0')
botao_n6.configure(text='6')
#botao_sair.configure(command=m.n1)

botao_n7= tk.Button()
botao_n7 .place(relx= 0.70,rely=0.17,width=100, height=45)
botao_n7.configure(activebackground='black')
botao_n7.configure(background="#d9d9d9")
botao_n7.configure(borderwidth = '5')
botao_n7.configure(disabledforeground="grey")
botao_n7.configure(font='-family{arial}-size 18')
botao_n7.configure(highlightbackground="grey")
botao_n7.configure(highlightcolor= "black")
botao_n7.configure(pady='0')
botao_n7.configure(text='7')
#botao_sair.configure(command=n7)

botao_n8 = tk.Button()
botao_n8 .place(relx= 0.774,rely=0.17,width=100, height=45)
botao_n8.configure(activebackground='black')
botao_n8.configure(background="#d9d9d9")
botao_n8.configure(borderwidth = '5')
botao_n8.configure(disabledforeground="grey")
botao_n8.configure(font='-family{arial}-size 18')
botao_n8.configure(highlightbackground="grey")
botao_n8.configure(highlightcolor= "black")
botao_n8.configure(pady='0')
botao_n8.configure(text='8')
#botao_sair.configure(command=m.8)

botao_n9 = tk.Button()
botao_n9 .place(relx= 0.847,rely=0.17,width=100, height=45)
botao_n9.configure(activebackground='black')
botao_n9.configure(background="#d9d9d9")
botao_n9.configure(borderwidth = '5')
botao_n9.configure(disabledforeground="grey")
botao_n9.configure(font='-family{arial}-size 18')
botao_n9.configure(highlightbackground="grey")
botao_n9.configure(highlightcolor= "black")
botao_n9.configure(pady='0')
botao_n9.configure(text='9')
#botao_sair.configure(command=m.9)

botao_soma = tk.Button()
botao_soma .place(relx= 0.92,rely=0.17,width=100, height=45)
botao_soma.configure(activebackground='black')
botao_soma.configure(background="#d9d9d9")
botao_soma.configure(borderwidth = '5')
botao_soma.configure(disabledforeground="grey")
botao_soma.configure(font='-family{arial}-size 18')
botao_soma.configure(highlightbackground="grey")
botao_soma.configure(highlightcolor= "black")
botao_soma.configure(pady='0')
botao_soma.configure(text='+')
#botao_sair.configure(command=m.+)

botao_sub = tk.Button()
botao_sub .place(relx= 0.92,rely=0.235,width=100, height=45)
botao_sub.configure(activebackground='black')
botao_sub.configure(background="#d9d9d9")
botao_sub.configure(borderwidth = '5')
botao_sub.configure(disabledforeground="grey")
botao_sub.configure(font='-family{arial}-size 18')
botao_sub.configure(highlightbackground="grey")
botao_sub.configure(highlightcolor= "black")
botao_sub.configure(pady='0')
botao_sub.configure(text='-')
#botao_sair.configure(command=m.-)

botao_div= tk.Button()
botao_div .place(relx= 0.92,rely=0.368,width=100, height=45)
botao_div.configure(activebackground='black')
botao_div.configure(background="#d9d9d9")
botao_div.configure(borderwidth = '5')
botao_div.configure(disabledforeground="grey")
botao_div.configure(font='-family{arial}-size 18')
botao_div.configure(highlightbackground="grey")
botao_div.configure(highlightcolor= "black")
botao_div.configure(pady='0')
botao_div.configure(text='/')
#botao_sair.configure(command=m.-)

botao_mult= tk.Button()
botao_mult .place(relx= 0.92,rely=0.3,width=100, height=45)
botao_mult.configure(activebackground='black')
botao_mult.configure(background="#d9d9d9")
botao_mult.configure(borderwidth = '5')
botao_mult.configure(disabledforeground="grey")
botao_mult.configure(font='-family{arial}-size 18')
botao_mult.configure(highlightbackground="grey")
botao_mult.configure(highlightcolor= "black")
botao_mult.configure(pady='0')
botao_mult.configure(text='X')
#botao_sair.configure(command=botao_mult)

botao_igual= tk.Button()
botao_igual .place(relx= 0.847,rely=0.368,width=100, height=45)
botao_igual.configure(activebackground='black')
botao_igual.configure(background="#d9d9d9")
botao_igual.configure(borderwidth = '5')
botao_igual.configure(disabledforeground="grey")
botao_igual.configure(font='-family{arial}-size 18')
botao_igual.configure(highlightbackground="grey")
botao_igual.configure(highlightcolor= "black")
botao_igual.configure(pady='0')
botao_igual.configure(text='=')
#botao_sair.configure(command=botao_igual)

botao_clean= tk.Button()
botao_clean .place(relx= 0.92,rely=0.105,width=100, height=45)
botao_clean.configure(activebackground='black')
botao_clean.configure(background="#d9d9d9")
botao_clean.configure(borderwidth = '5')
botao_clean.configure(disabledforeground="grey")
botao_clean.configure(font='-family{arial}-size 18')
botao_clean.configure(highlightbackground="grey")
botao_clean.configure(highlightcolor= "black")
botao_clean.configure(pady='0')
botao_clean.configure(text='C')
#botao_sair.configure(command=botao_clean)


janela.mainloop()


janela.mainloop()
